name: Deploy to WordPress

on:
  push:
    branches:
      - master  # replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/opt/lampp/htdocs/wordpress/wp-content/themes/twentytwentytwo"

    - name: Activate theme and plugins
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          wp theme activate twentytwentytwo --path=/opt/lampp/htdocs/wordpress
          wp plugin activate hello --path=/opt/lampp/htdocs/wordpress
