name: Execute remote SSH commands
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Execute remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Hello, world!"
